apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: python-kaniko
spec:
  containers:
    - name: python
      image: python:3.10-slim
      command:
        - cat
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/sh
      args:
        - -c
        - cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker

  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-secret
