apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent-role: flask
spec:
  containers:
    - name: python
      image: python:3.10-slim
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: 512Mi
          cpu: 300m
        limits:
          memory: 1Gi
          cpu: 600m
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
    - name: dind
      image: docker:24-dind
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      emptyDir: {}
